markdown: kramdown
permalink: /:title.html
url:
lsi: true
pygments: true
safe: true
auto: true
highlighter: rouge

# presonal config
title: "iCodingProgram"
feed: 
comments: disqus

author:
  name: 9drops
  nickname: 9drops
  email: zhanbz@hotmail.com
  site: http://www.icodingprogram.com

seo: 
  keyword: "iCodingProgram"
  description: "爱编程"
config:
  js_dir:
  img_dir:
  css_dir:
